### ISSUE TITLE
mixinf issue in 2D Law41 model

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#1257]
**Describe the bug**
During the evaluation of the LAW41 material, some issues where found.
- mixing not converged
- internal energy is in question
- contact deactivation is not working

**To Reproduce**
Run one of the models from the attachment.

**Expected behavior**
No "MIX NOT CONVERGING" messages, internal energy should work as expected, contact should be able to deactivate.

**Output**
The desciption is in the pdf in the attachment.

**Desktop (please complete the following information):**
 - Version [commit id]
   338d87c234a4115edc522f98966b9de32838a477
linux   Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (x86_64), 3499 MHz,  64217 MB RAM,      0 MB swap
- Configuration [number of OpenMP threads, and MPI tasks]
Single CPU, double precision

**Additional context**

[issueLAW41.tar.gz](https://github.com/OpenRadioss/OpenRadioss/files/11029147/issueLAW41.tar.gz)

**Comment by SonSiont** [comment]
Here is the modified source:
[sigeps41.F.gz](https://github.com/OpenRadioss/OpenRadioss/files/11029273/sigeps41.F.gz)

**Comment by Schwoertzig** [comment]
Hi @SonSiont , 
thank you very much for this valuable effort of investigation and reporting. I am going to study this and I will keep you informed.
Best Regards

**Comment by Schwoertzig** [comment]
Hi @SonSiont ,
 
There are some news about material Law41 (Lee-Tarver).
 
The manual page was completly rewritten. Parameter names are now consistent with the ones from scientific community.
  - pdf page is attached
  - CFG file was updated consequently : 1ca9dbe45d41004a7816eb373784cec06e277ad4
  - Starter Listing file was updated consequently : 1ca9dbe45d41004a7816eb373784cec06e277ad4
 
The iterative solver used to solve the mixture law is going to be replaced. @roguic wrote its own version of the Brent's method : this version can be merged in OpenRadioss since it has no copyright/licence.

Thank you again for your report.

@Schwoertzig

**Comment by elequiniou** [comment]
Dear @SonSiont , please, did you get a chance to test again OpenRadioss after this improvement ? 
This would be great to have your feedback.
Kind Regards,
Eric

**Comment by elequiniou** [comment]
AS no more feedback and development done, I close this issue. Thanks!
