### ISSUE TITLE
How to output animation file at exact time ?

### ISSUE THREAD

**Issue by wgm096350** [OpenRadioss/OpenRadioss#1282]
Total time is 1.0s.
I want to output animation file at time 0.0, 0.05, 0.10, 0.15, ..., 0.90, 0.95, 1.00s, so I add control card
/ANIM/DT
       0.0      0.05
After execution, I observe that the acutual ouput times for the animation files are 0.0, 0.057560, 0.10553, 0.15349, ... , 0.90183, 0.95939s.
Thus, how could I output animation file exactly at time 0.0, 0.05, 0.10, 0.15, ..., 0.90, 0.95, 1.00s?

**Comment by MarianBulla** [comment]
This is due to your critical timestep within your simulation, which may be not constant (OpenRadioss trys to use always the max. colsest to critical timestep, at each cylce) and is not exactly dividable by 0.05 (its an odd and uneven value). 
You can force the timestep to be more even one, but still slightly below your critical timestep, by using the /DTIX keyword (please check it in the engine reference manual) in the engine file. This sould give you perfect times of your desired animation file output.
Hope it helps you ?
Thanks and best regards,
Marian

**Comment by wgm096350** [comment]
Dear Marian，
Thanks a lot. There seems to be no  "one click" solution to this problem. I will try the method you suggested.
Best regards,
