### ISSUE TITLE
Having trouble getting MPI working on linux

### ISSUE THREAD

**Issue by wmcnCG** [OpenRadioss/OpenRadioss#1876]
Can't find library when running mpi:
```
$ mpiexec -n 4 --map-by socket:PE=$OMP_NUM_THREADS --bind-to core $OPENRADIOSS_PATH/exec/engine_linux64_gf_ompi -i BIRD_WINDSHIELD_v1_0001.rad

engine_linux64_gf_ompi: error while loading shared libraries: libmpi_mpifh.so.40: cannot open shared object file: No such file or directory
```
I set the LD_LIBRARY_PATH. 

Anyone else run into this issue? I'm using a Google Cloud c3-standard-8 instance. I'm thinking openmpi didn't install correctly..

Thanks in advance

**Comment by OlivierWienholtz** [comment]
Hello,

Radioss needs the Fortran interface from OpenMPI.
Indeed the issue comes from OpenMPI which has not been build against this interface.
How have you installed OpenMPI ? 

did you recompile it ? 

I recommend to install gfortran in addition to gcc & rebuild OpenMPI. The configure script will reconize the Gfrotran & add the Fortran MPI modules.

Olivier

**Comment by wmcnCG** [comment]
I installed gfortran before building OpenMPI and it is now working. Thank you!
