### ISSUE TITLE
Unexplained reaction force

### ISSUE THREAD

**Issue by hitotech1221** [OpenRadioss/OpenRadioss#2807]
[radbug.zip](https://github.com/user-attachments/files/16189684/radbug.zip)
I am looking at the reaction forces of the boundary conditions and the axial forces of the truss elements by giving displacements in this model solid_disp.k, but the values in the csv output are wrong.
On the other hand, the load-bearing model solid_force.k outputs the displacements and the axial force of the truss correctly.

The relevant parts of the csv are there. solid_dispT01.csv
These force outputs are not correct.
DATABASE_HISTORY_BEAM                    561                                          var 30
TH_NODE_BNDOUT                           464                                          var 44

The relationship between displacement and load here is just right.　solid_forceT01.csv
DATABASE_HISTORY_NODE                    464                                          var 35
DATABASE_HISTORY_BEAM                    561                                          var 30

**Comment by sebastienVilleneuve** [comment]
Hi @hitotech1221 

In T01 file , forces are stored as impulses.
To be able to have them derivated to output forces by the th->csv tool , you need to put /TH/TITLES in your 1.rad file .

cf https://github.com/OpenRadioss/Tools/tree/main/output_converters/th_to_csv

![image](https://github.com/user-attachments/assets/b6a2e089-c305-4799-b5cf-30535c4332e6)


I hope this helps

Thanks,
Sébastien

**Comment by hitotech1221** [comment]
HI @sebastienVilleneuve 

Thank you for your reply.
I got the solution for my issue by your infomation.

**Comment by MarianBulla** [comment]
Hi @hitotech1221,

Thanks for your info. This is great, that you were able to get the solution !

I will close this issue, now.
Since it seems to be solved.

Please feel free to reopen it, if it is still not solved. 
Or open a new one, if you face an issue or possible bug.

For other questions and/or discussion items, please review also the discussion forum, here at this repo.
There are already a lot of other points, discussed there :-) 

Hope it helps you ?

Thanks and best regards,
Marian
