### ISSUE TITLE
Issue with retractor / seatbelts since Version 3c0637dfd

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#3080]
**Describe the bug**
A model with seatbelt stuff does not work anymore. Forces and displacements increased by orders of magnitude.

**To Reproduce**
Run the files conrad_0000.rad and compare the csv files as in the png files. 

**Expected behavior**
RADIOSS should work at least as well as the old version.

**Output**
The attached archive contains the input and output files.
[beltRetraIssue.tar.gz](https://github.com/user-attachments/files/17445272/beltRetraIssue.tar.gz)

![R1_5cf878c57](https://github.com/user-attachments/assets/bb118ad4-9a6e-450a-a22d-54ee8067a19e)
![R1_3c0637dfd](https://github.com/user-attachments/assets/92e11a82-d117-42eb-9a1d-46d072632e92)

**Desktop (please complete the following information):**
 - Version [3c0637dfdc5d3eb6fd1c86959914baddaba3ff5c],
 - Version [5cf878c57e2f5792e3a31db20429b8e983cbc06d].
- Hardware [Linux; Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (x86_64), 3499 MHz,  64217 MB RAM]
- Configuration [SMP with two cores]

**Additional context**
In addition: When using RADIOSS with the LS-DYNA interface with retractor.k, the starter dies without any message.

**Comment by SonSiont** [comment]
To the LS-DYNA interface:
When add.rad is completed with a header, RADIOSS starter run and give an appropriate error message.
```
#RADIOSS STARTER
/BEGIN
additions
      2024         0
                  Mg                  mm                   s
                  Mg                  mm                   s
/TH/NODE/29999
_DBH_NODE
        DZ        VZ
        41         0_DBH_SPC
/END
```

**Comment by bertrand-altair** [comment]
Hi SonSiont,

Thanks for reporting the issue. In fact before the latest modification, the behavior was also incorrect at some point but able to go to the end. After the latest modification the behavior was better but another issue was revealed. The new issue is related to the slipring and friction with ED_factor > 0. It is fixed by commit  https://github.com/OpenRadioss/OpenRadioss/commit/ad1a0ecbe413d1ff480654de8a3ef3b711dbc6e8. Please try again with latest version.

![image](https://github.com/user-attachments/assets/4f4a369a-2628-47e5-9b63-0c42aae63c64)

Regards,

Bertrand,

**Comment by SonSiont** [comment]
Hi Bertrand,

it seems to be OK now.
I'm sorry about my bad model. It's much better with a bit of damping.
Regards, SonSiont

**Comment by bertrand-altair** [comment]
Hi Sonsiont,

Very good validation model in fact, that helps to find bugs.

Regards,

Bertrand,
